/*
Logto API references

Testing VerificationCodesAPIService

*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech);

package openapi

import (
	"context"
	"testing"

	openapiclient "github.com/lbf38/logto_provisioning"
	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

func Test_openapi_VerificationCodesAPIService(t *testing.T) {

	configuration := openapiclient.NewConfiguration()
	apiClient := openapiclient.NewAPIClient(configuration)

	t.Run("Test VerificationCodesAPIService CreateVerificationCode", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.VerificationCodesAPI.CreateVerificationCode(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

	t.Run("Test VerificationCodesAPIService VerifyVerificationCode", func(t *testing.T) {

		t.Skip("skip test") // remove to run test

		httpRes, err := apiClient.VerificationCodesAPI.VerifyVerificationCode(context.Background()).Execute()

		require.Nil(t, err)
		assert.Equal(t, 200, httpRes.StatusCode)

	})

}
